[package]
name = "hdfs-protos"
version = "0.1.0"
authors = ["Daniel Rammer <hamersaw@bushpath.com>"]
edition = "2018"

build = "build.rs"

[dependencies]
prost = "0.5"
bytes = "0.4"

[build-dependencies]
prost-build = "0.5"
